#TODO: ‘may not’ (but ‘may’ counts as keyword for a right, see under 2.a/)

primary_duties=[
    'agree',
    'agrees',
    'duty',
    'you will',
    'must',
    'has to',
    'is required',
    'requires',
    'warrant',
    'warrants',
    'you shall',
    'obligated',
    'is liable',
    'is responsible for',
    'responsibility',
    'obligation',
    'obligations',
    'must not',
    'not permitted',
    'shall not',
    'shall NOT',
    'will not',
    'not eligible',
    'nor shall you'
    'accept',
    'accepts'
]

duty_helpers=[
    'shall',
    'is to',
    'to be',
    'acknowledge',
    'acknowledges',
    'accept',
    'accepts',
    'understands'
]

secondary_duties=[
    'penalty',
    'fee',
    'pay',
    'due',
    'responsibility',
    'duties',
    'responsible',
    'expense',
    'charge',
    'charged',
    'prohibited',
    'permitted only',
    'obligation',
    'responsibility',
    'resign',
    'terminate',
    'notified',
    'made',
    'costs',
    'accompanied by',
    'reimbursed',
    'day',
    'days',
    'month',
    'monts',
    'week',
    'weeks',
    'indemnify',
    'do',
    'perform',
    'assist',
    'devote',
    'hold',
    'disclosed',
    'provide',
    'reimburse'
]